export default {
  TITULO_BUSCADOR: 'Buscador de Tiendas',
  TITULO_BUSCADOR_GASTRO: 'Buscador gastronómico',
  TITULO_TRAZA_RUTA: 'Encuentra tu tienda',
  SUBTITULO_TRAZA_RUTA: 'Encuentra tu tienda favorita',
  SUBTITULO_BUSCADOR: 'Encuentra tu tienda favorita',
  SUBTITULO_BUSCADOR_GASTRO: 'Encuentra tu restaurante favorito',
  TITULO_BUSCADOR_CATEOGORIA: 'Buscador de Categorías',
  LBL_TIENDA: 'Tiendas',
  LBL_RESTAURANTE: 'Restaurantes',
  LBL_CATEGORIAS: 'Categor&iacute;as',
  PH_TIENDAS: 'Tienda',
  PH_CATEGORIAS: 'Categorías (Ingresa más de un caracter)',
  LIMIT_ITEMS: 30,
  SKIP_PAGE: 0,
  TIPOS_DE_POI: [2, 6],
  TIPOS_DE_POI_GASTRO: [6],
  CATEGORIAS_GASTRONOMIA: '6',
  ESTADO_POI: [1, 6],
  ESTADO_ABIERTO: [1],
  CONFIG: {
    searchUrl: 'pois/smartsearch?q=',
    searchStoresUrl: 'pois/allCustomer',
    searchStoresTravellersUrl: 'pois/traveller',
    searchStoresByCategoryUrl: 'pois/storesBycategory?limit=10000',
    searchCategoriesUrl: 'categories/search?limit=10000',
    minLengthCharacters: 2,
  },
  URL_DETAIL_STORE: `${window.liquid.siteUrl}/tiendas/detalle?q=`,
};
